pub enum Command {
    Hello {
        version: Option<i64>,
        auth: Option<(String, String)>,
    },
    Get(String),
    Set(String, String),
    Del(Vec<String>),
    Exists(Vec<String>),
    Incr(String),
    IncrBy(String, i64),
    Decr(String),
    DecrBy(String, i64),
    Expire(String, i64),
    Ttl(String),
    HGet(String, String),
    HSet(String, String, String),
    Append(String, String),
    Ping(Option<String>),
    Info,
    Command,
    Client,
}
